# Generated by Django 4.0.3 on 2022-06-03 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbl_admin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='count',
            new_name='total',
        ),
        migrations.AddField(
            model_name='device',
            name='image',
            field=models.TextField(default='Image Devices'),
        ),
    ]
