# Generated by Django 4.0.3 on 2022-06-20 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbl_admin', '0002_rename_count_device_total_device_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='image',
            field=models.ImageField(upload_to='Image_devices/'),
        ),
    ]
