# Generated by Django 4.0.3 on 2022-06-20 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbl_admin', '0003_alter_device_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='image',
            field=models.ImageField(blank=True, upload_to='Image_devices/'),
        ),
    ]
